AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance without tags'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0123456789abcdef0
      SecurityGroups:
        - default