AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with existing tags'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-example-bucket
      Tags:
        - Key: ExistingTag
          Value: ExistingValue
        - Key: Environment
          Value: Development