AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template with resources that do not support tags'

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

  MyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /my/parameter
      Type: String
      Value: my-value